[build]
  base = "."
  command = "pip install -r requirements.txt && cd rag-frontend && npm install && npm run build"
  publish = "rag-frontend/build"
  
[build.environment]
  PYTHON_VERSION = "3.11.9"
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
yvv-xnad-ckv
