[build]
  base = "."
  command = "pip install -r requirements.txt && cd frontend && npm install && npm run build"
  publish = "frontend/build"
  
[build.environment]
  PYTHON_VERSION = "3.11.9"
  NODE_VERSION = "18"
